CREATE TYPE "AvailabilityStatus" AS ENUM ('UNSPECIFIED', 'OPEN_TO_WORK', 'EMPLOYED', 'NOT_LOOKING', 'FREELANCE_OPEN');

ALTER TABLE "User" ADD COLUMN "availabilityStatus" "AvailabilityStatus" NOT NULL DEFAULT 'UNSPECIFIED';
