export const FIRST_NAMES = [
  'Mira',
  'Jon',
  'Sam',
  'Alex',
  'Taylor',
  'Casey',
  'Priya',
  'Marcus',
  'Sofia',
  'James',
  'Elena',
  'Viktor',
  'Amara',
  'Diego',
  'Yuki',
  'Fatima',
  'Henrik',
  'Zara',
  'Omar',
  'Ingrid',
  'Rohan',
  'Nina',
  'Kai',
  'Lucia',
  'Thiago',
  'Aisha',
  'Leo',
  'Freya',
  'Mateo',
  'Noor',
  'Soren',
  'Isla',
  'Arjun',
  'Clara',
  'Emil',
  'Mei',
  'Idris',
  'Sofia',
  'Ren',
  'Hana',
  'Felix',
  'Anika',
  'Theo',
  'Lina',
  'Nikolai',
  'Esme',
  'Javier',
  'Rumi',
  'Quinn',
  'Ava',
  'Dante',
  'Mira',
  'Sasha',
  'Rowan',
  'Keiko',
  'Ivan',
  'Nadia',
  'Ezra',
  'Priya',
  'Luca',
  'Yara',
  'Oscar',
  'Tara',
  'Kofi',
  'Helena',
  'Rafael',
  'Jun',
  'Ada',
  'Malik',
  'Sienna',
  'Vera',
  'Tomás',
] as const

export const LAST_NAMES = [
  'Okonkwo',
  'Patel',
  'Rivera',
  'Chen',
  'Kim',
  'Wu',
  'Shah',
  'Lee',
  'Torres',
  'Kwon',
  'Vasquez',
  'Lindqvist',
  'Hassan',
  'Morales',
  'Tanaka',
  'Al-Farsi',
  'Berg',
  'Okonkwo',
  'Haddad',
  'Nielsen',
  'Kapoor',
  'Petrov',
  'Silva',
  'Nakamura',
  'Rahman',
  'Johansson',
  'Kowalski',
  'Santos',
  'Yamamoto',
  'Khan',
  'Olsen',
  'Nowak',
  'Costa',
  'Suzuki',
  'Abbas',
  'Larsen',
  'Kaminski',
  'Oliveira',
  'Sato',
  'Hassan',
  'Müller',
  'Wójcik',
  'Ferreira',
  'Ito',
  'Farouk',
  'Andersen',
  'Zielinski',
  'Rodríguez',
  'Watanabe',
  'Ibrahim',
  'Kristensen',
  'Mazur',
  'Alves',
  'Kobayashi',
  'Mahmoud',
  'Nielsen',
  'Pawlak',
  'Ribeiro',
  'Nakamura',
  'Osei',
  'Larsson',
  'Krawczyk',
  'Carvalho',
  'Tanaka',
  'Saeed',
  'Sørensen',
  'Wieczorek',
  'Gomes',
  'Yamaguchi',
  'Darwish',
  'Eriksen',
  'Jabłoński',
  'Martins',
  'Inoue',
  'Aziz',
  'Mikkelsen',
  'Dąbrowski',
  'Lopes',
  'Fujita',
  'Hakim',
  'Holm',
  'Piotrowski',
  'Rocha',
  'Matsuda',
  'Karimi',
  'Bergström',
  'Grabowski',
  'Teixeira',
  'Abe',
  'Nassar',
] as const

export const TAGLINES = [
  'Ships on Fridays, sleeps on Saturdays.',
  'Rust for breakfast, graphs for dinner.',
  'Breaking prod so you do not have to.',
  'Typing fast until the problem surrenders.',
  'Logs are my love language.',
  'I read RFCs for fun.',
  'Postgres first, questions later.',
  'CI green is my aesthetic.',
  'Latency is a bug.',
  'Scale is a habit.',
  'I delete code more than I write it.',
  'Feature flags are my safety blanket.',
  'Observability or it did not happen.',
  'Idempotency is my middle name.',
  'WebSockets at dawn.',
  'Kubernetes with feelings.',
  'Monolith enjoyer.',
  'Microservices survivor.',
  'API design is UX.',
  'Security is a feature.',
  'Tests are documentation.',
  'Types are contracts.',
  'Caching is cheating legally.',
  'Queues over chaos.',
  'Backpressure is mindfulness.',
  'On-call and still smiling.',
  'PagerDuty is my alarm clock.',
  'SLOs over vibes.',
  'Canary in the coal mine.',
  'Trunk-based optimist.',
  'Feature branches realist.',
  'Code review is a conversation.',
  'DRY until it hurts.',
  'WET when it helps.',
  'YAML engineer.',
  'Terraform enjoyer.',
  'Bash is a language.',
  'SQL is my superpower.',
  'GraphQL skeptic, REST fan.',
  'REST skeptic, GraphQL fan.',
  'Open source contributor.',
  'Night owl, green deploys.',
  'Coffee, then distributed systems.',
  'Tea, then refactors.',
  'Pair programming advocate.',
  'Async all the things.',
  'Sync when it matters.',
  'Zero-downtime mindset.',
  'Rollback plan ready.',
  'Chaos engineering curious.',
  'Load testing enjoyer.',
  'Profiling is self-care.',
  'Memory leaks fear me.',
  'Race conditions found me first.',
  'Deadlocks are puzzles.',
  'Threads are friends.',
  'Green threads, blue skies.',
  'Event-driven life.',
  'CRDTs for breakfast.',
  'Consensus is hard.',
  'Raft enthusiast.',
  'Paxos understander.',
  'CAP theorem haunts me.',
  'Eventually consistent human.',
  'Strong consistency advocate.',
  'ACID enjoyer.',
  'BASE believer.',
  'NoSQL when needed.',
  'SQL always.',
  'ORM pragmatist.',
  'Raw SQL artist.',
  'Migrations without tears.',
  'Blue-green deploys.',
  'Feature toggles everywhere.',
  'Dark mode default.',
  'Accessibility first.',
  'Keyboard navigator.',
  'Screen reader friendly.',
  'Perf budgets enforced.',
  'Bundle size watcher.',
  'Tree-shaking believer.',
  'Lazy loading life.',
  'SSR when it counts.',
  'CSR when it ships.',
  'Edge curious.',
  'CDN enjoyer.',
  'Static site maximalist.',
  'Serverless where it fits.',
  'Containers everywhere else.',
  'Bare metal enjoyer.',
  'Virtual machines nostalgic.',
  'Documentation writer.',
  'README driven.',
  'Changelog maintainer.',
  'Semver respecter.',
  'Breaking changes carefully.',
  'Deprecation notices always.',
  'OpenAPI fan.',
  'gRPC curious.',
  'Protobuf enjoyer.',
  'JSON Schema validator.',
  'Zod enjoyer.',
  'TypeScript maximalist.',
  'Python for scripts.',
  'Go for services.',
  'Rust for tools.',
  'Ruby for joy.',
  'Elixir curious.',
  'Kotlin for Android.',
  'Swift for iOS.',
  'Cross-platform dreamer.',
] as const
